name: Rust
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      c_digits:
        description: "Length of composites to process, in decimal digits"
        required: false
        type: number
      u_digits:
        description: "Length of unknown-status numbers to process, in decimal digits"
        required: false
        type: number
      prp_digits:
        description: "Length of probable primes to process, in decimal digits"
        required: false
        type: number
      prp_start:
        description: "Number of probable primes to skip before the first one to process"
        required: false
        type: number
      chosen_c:
        # FIXME: not currently implemented by the Rust program
        description: "Specific composites to factor, separated by spaces"
        required: false
        type: string
  workflow_call:
    inputs:
      sub_run_id:
        description: "ID of the sub-run to process"
        required: true
        type: number
env:
  CARGO_TERM_COLOR: always
  C_DIGITS: ${{ inputs.c_digits }}
  U_DIGITS: ${{ inputs.u_digits }}
  PRP_DIGITS: ${{ inputs.prp_digits }}
  PRP_START: ${{ inputs.prp_start }}
  SUB_RUN: ${{ inputs.sub_run_id }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate deadline
        id: set_deadline
        run: |
          DEADLINE=$(($(date +%s) + 19800)) # 5h30m
          echo "deadline=$DEADLINE" >> $GITHUB_OUTPUT
          echo "Deadline Unix timestamp: $DEADLINE"
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Needed for git-restore-mtime-action
      - name: Restore timestamps # Prevents an unnecessary rebuild
        uses: chetan/git-restore-mtime-action@v2
      - name: Cache apt/dpkg
        uses: actions/cache@v6
        with:
          path: |
            /usr/bin/ecm
            /usr/lib/x86_64-linux-gnu/libecm.a
            /var/cache/apt/archives/*.deb
            /var/lib/dpkg/status
          key: dpkg-ecm-2025-11-17
      - name: Detect native CPU target
        id: get_target_cpu
        run: |
          target_cpu=$(rustc --print target-cpus | grep native | grep -o 'currently .*)' | grep -o '[A-Za-z0-9_-]*)$')
          echo "target_cpu=${target_cpu::-1}" >> $GITHUB_OUTPUT
      - name: Cache Cargo dependencies
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo
            target
            Cargo.lock
          key: cargo-${{ steps.get_target_cpu.outputs.target_cpu }}-${{ hashFiles('.github/workflows/rust.yml', '**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ steps.get_target_cpu.outputs.target_cpu }}-
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Build while installing runtime dependencies
        run: |
          (
            sudo apt-get update
            sudo apt-get install -y libecm-dev gmp-ecm
          ) &
          ./build.sh
      - name: Run
        env:
          DEADLINE: ${{ steps.set_deadline.outputs.deadline }}
          RUN: ${{ github.run_number }}
          SUB_RUN: ${{ inputs.sub_run_id }}
          C_DIGITS: ${{ inputs.c_digits }}
          U_DIGITS: ${{ inputs.u_digits }}
          PRP_DIGITS: ${{ inputs.prp_digits }}
          PRP_START: ${{ inputs.prp_start }}
          NO_RESERVE: 1
        run: |
          set -x
          if [ "${{github.event_name}}" == "push" ]; then
            export RUST_BACKTRACE=full
          fi
          ./target/release/FactorBot "${{ steps.set_deadline.outputs.deadline }}"
      - name: Upload any failed submissions
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Failed submissions
          path: 'failed-*.csv'
          if-no-files-found: ignore
